DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS court;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE court (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  reserved TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  sport TEXT NOT NULL,
  num INTEGER NOT NULL,
  FOREIGN KEY (user_id) REFERENCES user (id)
);